services:

  prod-api:
    image: api-openskimap-org
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - ARANGODB_URL=http://arangodb:8529/
    networks:
      - db
    depends_on:
      - arangodb

  arangodb:
    image: arangodb:3.12.1
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=offskimap
    networks:
      - db
    volumes:
      - ./data:/var/lib/arangodb3

networks:
  db:
