services:
  app:
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - ARANGODB_URL=http://arangodb:8529/
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    command: 'sh -c "sleep 5 && npm run build && npm run start"'
    networks:
      - db
    depends_on:
      - arangodb
  arangodb:
    image: arangodb:3.12.1
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1d
    networks:
      - db
networks:
  db:
